version: '3.5'

services:
  ictp:
    container_name: ictp
    build:
      dockerfile: Dockerfile
      context: .
      target: development
    env_file:
      - .env
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - "${APP_PORT}:4000"
    command: yarn start:dev
    depends_on:
      - db
    restart: always
  db:
    container_name: db
    image: postgres:16
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - pgdata:/var/lib/postgresql/16/data
    restart: always
volumes:
  pgdata: {}
